routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




//Login routes


Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['web', 'auth']], function () {

    //Default route - Dashboard
    Route::get('/', "HomeController@redirectHome")->name('redirect');
    Route::get('/home', 'HomeController@index')->name('home');

    //Localization route
    Route::get('/language/{locale}', "LanguageController@changeLanguage")->name('locale');

    //Account/Profile routes
    Route::get('/profile', 'ProfileSettingsController@index')->name('profile');

    //Employees routes
    Route::resource('employees', 'EmployeesController');
    Route::post('/employees/list', 'EmployeesController@dataTable')->name('employees.datatable');
    Route::post('/employees/{employee}/documents','EmployeesController@documents')
        ->name('employees.upload-documents');
    Route::get('/employees/{employee}/documents/delete','EmployeesController@removeDocumentsView')
        ->name('employees.remove-documents-view');
    Route::get('/employees/{employee}/documents','EmployeesController@getDocuments')
        ->name('employees.add-documents');
    Route::get('/employees/{employee}/photos','EmployeesController@getPhotos')
        ->name('employees.photos');
    Route::delete('/employees/documents/{id}','EmployeesController@deleteDocument')
        ->name('employees.delete-document');
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class Employee extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $table = 'employees';
    protected $fillable = ['first_name','last_name', 'birthday', 'phone', 'email', 'address', 'ssn'];

    public static function deletePhoto($id)
    {
        $photo = DB::table('employees_photos')->where('id','=', $id);
        $photoDetails = $photo->first();
        $employee = $photoDetails->employee_id;
        $file = $photoDetails->file_name;
        Storage::delete('/public/documents/' . $employee . "/" . $file);
        $photo->delete();
        return true;
    }


    public function addDocument($name) {
        $id = $this->id;
        DB::table('employees_photos')->insert([
            'file_name' => $name,
            'description' => $name,
            'employee_id' => $id
        ]);
    }

    public function getPhotos()
    {
        $id = $this->id;
        $photos = DB::table('employees_photos')
            ->where('employee_id', '=', $id)
            ->get(['id', 'file_name'])
            ->toArray();
        return $photos;
    }

    public function hasDocuments() {
        $id = $this->id;
        $photos = DB::table('employees_photos')
            ->where('employee_id', '=', $id)
            ->get(['id'])
            ->count();
        return $photos;
    }
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\Helpers\DateConverter;
use App\Helpers\EmployeeFilter;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.employees.index')->with('on_employees', true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.employees.create')->with('on_employees', true);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $input['birthday'] = DateConverter::dateToDBConverter($input['birthday']);
        $newEmployee = new Employee();
        $newEmployee->fill($input);
        $newEmployee->save();
        return view('pages.employees.add-photos-middle')
            ->with('employee', $newEmployee)->with('on_employees', true);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        $employee->birthday = DateConverter::dateFromDBConverter($employee->birthday);
        return view('pages.employees.full-data')->with('employee', $employee);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $employee->birthday = DateConverter::dateFromDBConverter($employee->birthday);
        return view('pages.employees.update')
            ->with('employee', $employee)->with('on_employees', true);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $input = $request->all();
        $input['birthday'] = DateConverter::dateToDBConverter($input['birthday']);
        $employee->fill($input);
        $employee->save();
        return redirect()->route('employees.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return json_encode(['status' => 1]);
    }


    public function dataTable(Request $request) {
        $search = $request->input();
        $datatable = new EmployeeFilter();
        $response = $datatable->filter($search);
        return json_encode($response);
    }

    public function documents(Request $request, Employee $employee) {
        $acceptedTypes = ['jpg', 'jpeg', 'png'];
        $mime = $request->file('file')->getClientMimeType();
        $size = $request->file('file')->getSize();
        if($size < 5000000) {
            $type = explode('/',$mime);
            if(count($type) === 2 && $type[0] === "image" && in_array($type[1], $acceptedTypes)) {
                $content = $request->file('file');
                if (!File::isDirectory(storage_path() . '/app/public/documents/' . $employee->id)) {
                    File::makeDirectory(storage_path(). '/app/public/documents/' . $employee->id);
                }
                $name = uniqid() . '.' . $type[1];
                $status = Storage::putFileAs('public/documents/' . $employee->id, $content, $name);
                if($status) {
                    $employee->addDocument($name);
                } else {
                    return response(json_encode('Error on file upload.'),400);
                }
            } else {
                return response(json_encode('Bad file type.'),400);
            }
        } else {
            return response(json_encode('File too big.'),400);
        }
    }

    public function getDocuments(Employee $employee) {
        return view('pages.employees.add-photos')->with('employee', $employee)->with('on_employees', true);
    }

    public function getPhotos(Employee $employee) {
        $photos = $employee->getPhotos();
        return response(json_encode($photos));
    }

    public function removeDocumentsView(Employee $employee) {
        $photos = $employee->getPhotos();
        return view('pages.employees.remove-photos')->with('photos',$photos)->with('employee', $employee)->with('on_employees', true);
    }

    public function deleteDocument($id) {
        $status = Employee::deletePhoto($id);
        if($status) {
            return response(json_encode(['status'=> 1]),200);
        } else {
            response(json_encode(['status' => 0]), 400);
        }
    }

}

resources/views/pages/employees/add-photos-middle.blade.php
@extends('layouts.app')
@section('content')
    <input type="hidden" @if($employee) value="{{$employee->id}}" @endif id="employee-id">
@endsection
@section('extra-footer-scripts')
    <script>
        $(document).ready(function () {
            var id = $("#employee-id").val();
            if(id) {
                window.location.href = "/employees/" + id + "/documents"
            } else {
                window.location.href = "/employees/"
            }
        })
    </script>
@endsection

resources/views/pages/employees/add-photos.blade.php
@extends('layouts.app')

@section('title')
    @lang('employees.documents')
@endsection


@section('portlet-healer-icon')
    <span class="m-portlet__head-icon"><i class="fa fa-film"></i></span>
@endsection


@section('portlet-header')
    @lang('employees.add_documents_for') {{$employee->first_name . ' ' . $employee->last_name}}
@endsection


@section('header')
    @include('includes.breadcumb', [
            'module' => Lang::get('employees.employees_lbl'),
            'menues' => [[
                'route' => '/employees',
                'name' => Lang::get('employees.menu_1')
                ],[
                'route' => '#',
                'name' => Lang::get('employees.menu_2')
                ]
            ]])
@endsection


@section('content')
    <div class="form-group m-form__group row">
        <label class="col-form-label col-lg-3 col-sm-12">
            @lang('employees.add_documents_phots')
        </label>
        <div class="col-lg-4 col-md-9 col-sm-12">
            <form class="m-dropzone dropzone m-dropzone--brand dz-clickable"
                 action="{{route('employees.upload-documents', ['employee' => $employee->id])}}" id="documentsdropzone">
                {{csrf_field()}}
                <div class="m-dropzone__msg dz-message needsclick">
                    <h3 class="m-dropzone__msg-title">
                        @lang('employees.add_documents_phots')
                    </h3>
                    <span class="m-dropzone__msg-desc">@lang('employees.only_images')</span>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9 ml-lg-auto">
            <button type="button" class="btn btn-brand" id="done-adding-photos">
                @lang('common.done')
            </button>
        </div>
    </div>
@endsection


@section('extra-footer-scripts')
    <script src="{{asset('js/employees/photos.js')}}"></script>
@endsection

resources/views/pages/employees/create.blade.php
@extends('layouts.app')
@section('title')
    @lang('employees.add_page')
@endsection
@section('portlet-header')
    @lang('employees.new_page')
@endsection
@section('header')
    @include('includes.breadcumb', [
            'module' => Lang::get('employees.employees_lbl'),
            'menues' => [[
                'route' => '/employees',
                'name' => Lang::get('employees.menu_1')
                ],[
                'route' => '#',
                'name' => Lang::get('employees.menu_add')
                ]
            ]])
@endsection
@section('content')
    <form id="add-employees-form" method="post" action="{{route('employees.store')}}">
        {{csrf_field()}}
        <div class="m-form__section m-form__section--first">
            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.f_name'):
                </label>
                <div class="col-lg-6">
                    <input type="text" name="first_name" class="form-control m-input" placeholder="@lang('employees.f_name_prompt')">
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.l_name'):
                </label>
                <div class="col-lg-6">
                    <input type="text" name="last_name" class="form-control m-input" placeholder="@lang('employees.l_name_prompt')">
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.contact')
                </label>
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="email" name="email" class="form-control m-input has-addon" placeholder="@lang('employees.email_prompt')">
                        <span class="input-group-addon"><i class="la la-envelope-o"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label"></label>
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" name="phone" class="form-control m-input has-addon" placeholder="@lang('employees.phone_prompt')">
                        <span class="input-group-addon"><i class="la la-phone"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.birthdate'):
                </label>
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" name="birthday" class="form-control m-input datepicker has-addon" placeholder="@lang('employees.birthdate')">
                        <span class="input-group-addon"><i class="la la-calendar-o"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.address'):
                </label>
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" name="address" class="form-control m-input has-addon" placeholder="@lang('employees.address_prompt')">
                        <span class="input-group-addon"><i class="la la-map-marker"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.health_care'):
                </label>
                <div class="col-lg-6">
                    <input type="text" name="ssn" class="form-control m-input" placeholder="@lang('employees.ssn')">
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg-9 ml-lg-auto">
                    <button type="submit" class="btn btn-brand" id="create-employee-button">
                        @lang('common.submit')
                    </button>
                    <button type="reset" class="btn btn-secondary" id="close-button">
                        @lang('common.close')
                    </button>
                </div>
            </div>
        </div>
    </form>
@endsection
@section('extra-footer-scripts')
    <script src="{{asset('js/employees/create.js')}}"></script>
@endsection

resources/views/pages/employees/full-data.blade.php
<html>
<head>
    <script type="text/css">
        html {font-family: Poppins, sans-serif}
    </script>
</head>
<body>
<h1 align="center">@lang('employees.data')</h1>
<br />
<br />
<div class="container">
    <div class="row">
        <div style="width: 33%;display: inline-block">
            @lang('employees.f_name'):
        </div>
        <div style="width: 66%;display: inline-block">
            {{$employee->first_name}}
        </div>
        <div style="width: 33%;display: inline-block">
            @lang('employees.l_name'):
        </div>
        <div style="width: 66%;display: inline-block">
            {{$employee->last_name}}
        </div>
        <div style="width: 33%;display: inline-block">
            @lang('employees.birthdate'):
        </div>
        <div style="width: 66%;display: inline-block">
            {{$employee->birthday}}
        </div>
        <div style="width: 33%;display: inline-block">
            @lang('employees.address'):
        </div>
        <div style="width: 66%;display: inline-block">
            {{$employee->address}}
        </div>
        <div style="width: 33%;display: inline-block">
            @lang('employees.ssn'):
        </div>
        <div style="width: 66%;display: inline-block">
            {{$employee->ssn}}
        </div>
        <div style="width: 33%;display: inline-block">
            @lang('employees.phone'):
        </div>
        <div style="width: 66%;display: inline-block">
            {{$employee->phone}}
        </div>
        <div style="width: 33%;display: inline-block">
            @lang('employees.email')
        </div>
        <div style="width: 66%;display: inline-block">
            {{$employee->email}}
        </div>
    </div>
    <br/>
    <div class="row">
        @foreach($employee->getPhotos() as $photo)
            <div><img style="width: 100%" class="img-responsive" src="/storage/documents/{{$employee->id}}/{{$photo->file_name}}"></div>
        @endforeach
    </div>
</div>



<script src="{{asset('js/vendors.bundle.js')}}" type="text/javascript"></script>
<script src="{{asset('js/scripts.bundle.js')}}" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        window.print();
    })
</script>
</body>
</html>

resources/views/pages/employees/index.blade.php
@extends('layouts.app')
@section('title')
    @lang('employees.employees_vis')
@endsection
@section('portlet-header')
    @lang('employees.employees_lbl')
@endsection
@section('portlet-header-button')
    <a href="{{route('employees.create')}}" class="btn btn-brand">+ @lang('employees.add')</a>
@endsection
@section('header')
    @include('includes.breadcumb', [
            'module' => Lang::get('employees.employees_lbl'),
            'menues' => [[
                'route' => '#',
                'name' => Lang::get('employees.menu_1')
                ]
            ]])
@endsection
@section('content')
    <div>
                <div class="float-left">
                    <div class="input-group">
                        <span class="input-group-addon" id="sizing-addon2"><i class="fa fa-search"></i></span>
                        <input type="text" name="name" id="search-by-name" class="form-control" placeholder="@lang('employees.search_name')" aria-describedby="sizing-addon2">
                    </div>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
    <div>
        <div class="m_datatable" id="employees_table"></div>
    </div>
    @include('includes.delete-modal')
    @include('includes.images-modal')
@endsection
@section('extra-footer-scripts')
    <script src="{{asset('js/data-table.js')}}"></script>
    <script src="{{asset('js/modal-helper.js')}}"></script>
    <script src="{{asset('js/images-modal.js')}}"></script>
    <script src="{{asset('js/employees/index.js')}}"></script>
@endsection

resources/views/pages/employees/remove-photos.blade.php
@extends('layouts.app')
@section('title')
    @lang('employees.remove_doc')
@endsection
@section('portlet-header')
    @lang('employees.remove_doc_for') {{$employee->first_name . " " . $employee->last_name}}
@endsection


@section('header')
    @include('includes.breadcumb', [
            'module' => Lang::get('employees.employees_lbl'),
            'menues' => [[
                'route' => '/employees',
                'name' => Lang::get('employees.menu_1')
                ],[
                'route' => '/employees/' . $employee->id . '/edit',
                'name' => Lang::get('employees.edit'). " " . $employee->first_name . " " . $employee->last_name
                ],[
                'route' => '#',
                'name'  => 'Delete documents'
                ]
            ]])
@endsection
@section('content')
    @if($photos)
        <div id="regular-content">
            <div class="center-block" id="to-center-in">
                <div class="btn-group m-btn-group m-btn-group--pill" id="centered-in" role="group" aria-label="...">
                    <button type="button" class="m-btn btn btn-brand siema-prev">
                        <<
                    </button>
                    <button id="delete-photo-button" type="button" class="m-btn btn btn-brand">
                        <i class="la la-trash-o"></i>
                    </button>
                    <button type="button" class="m-btn btn btn-brand siema-next">
                        >>
                    </button>
                </div>
            </div>
            <br/>
            <div class="siema">
                @foreach($photos as $photo)
                    <img data-id="{{$photo->id}}" style="width: 100%; height: 100%" src="{{asset('storage/documents') . "/" . $employee->id . "/" . $photo->file_name}}">
                @endforeach
            </div>
        </div>
        <div hidden id="no-documents">
            <h1>{{Lang::get('employees.no_documents_for', ['name' => $employee->first_name . " " . $employee->last_name])}}<a href="/employees">@lang('employees.employees_lbl')</a></h1>
        </div>
    @else
        <script>
            window.location.href = '/employees'
        </script>
    @endif


    @include('includes.delete-modal')
@endsection
@section('extra-footer-scripts')
    <script src="{{asset('js/modal-helper.js')}}"></script>
    <script src="{{asset('js/vendor/siema.js')}}"></script>
    <script src="{{asset('js/employees/delete-photos.js')}}"></script>
@endsection

resources/views/pages/employees/update.blade.php
@extends('layouts.app')
@section('title')
    @lang('employees.edit_page')
@endsection
@section('portlet-header')
    {{Lang::get('employees.edit_for', ['name' => $employee->first_name . " " . $employee->last_name])}}
@endsection

@section('portlet-header-button')
    <a style="margin-right: 10px" href="{{route('employees.add-documents',['employee' => $employee->id])}}" class="btn btn-brand">+ @lang('employees.add_doc')</a>
    @if($employee->hasDocuments())
        <a href="{{route('employees.remove-documents-view',['employee' => $employee->id])}}" class="btn btn-danger">- @lang('employees.remove_doc')</a>
    @endif
@endsection

@section('header')
    @include('includes.breadcumb', [
            'module' => Lang::get('employees.employees_lbl'),
            'menues' => [[
                'route' => '/employees',
                'name' => Lang::get('employees.menu_1')
                ],[
                'route' => '#',
                'name' => Lang::get('employees.edit')
                ]
            ]])
@endsection
@section('content')
    <form id="add-employees-form" method="post" action="{{route('employees.update', ['id' => $employee->id])}}">
        <input type="hidden" name="_method" value="put" />
        {{csrf_field()}}
        <div class="m-form__section m-form__section--first">
            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.f_name'):
                </label>
                <div class="col-lg-6">
                    <input type="text" name="first_name" value="{{$employee->first_name}}" class="form-control m-input" placeholder="@lang('employees.f_name_prompt')">
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.l_name'):
                </label>
                <div class="col-lg-6">
                    <input type="text" name="last_name" value="{{$employee->last_name}}" class="form-control m-input" placeholder="@lang('employees.l_name_prompt')">
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.contact')
                </label>
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="email" name="email" value="{{$employee->email}}" class="form-control m-input has-addon" placeholder="@lang('employees.email_prompt')">
                        <span class="input-group-addon"><i class="la la-envelope-o"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label"></label>
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" name="phone" value="{{$employee->phone}}" class="form-control m-input has-addon" placeholder="@lang('employees.phone_prompt')">
                        <span class="input-group-addon"><i class="la la-phone"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.birthdate'):
                </label>
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" name="birthday" value="{{$employee->birthday}}" class="form-control m-input datepicker has-addon" placeholder="@lang('employees.birthdate')">
                        <span class="input-group-addon"><i class="la la-calendar-o"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.address'):
                </label>
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" name="address" value="{{$employee->address}}" class="form-control m-input has-addon" placeholder="@lang('employees.address_prompt')">
                        <span class="input-group-addon"><i class="la la-map-marker"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group m-form__group row">
                <label class="col-lg-3 col-form-label">
                    @lang('employees.health_care'):
                </label>
                <div class="col-lg-6">
                    <input type="text" name="ssn" value="{{$employee->ssn}}" class="form-control m-input" placeholder="@lang('employees.ssn')">
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg-9 ml-lg-auto">
                    <button type="submit" class="btn btn-brand" id="create-employee-button">
                        @lang('common.update')
                    </button>
                    <button type="button" class="btn btn-secondary" id="close-button">
                        @lang('common.close')
                    </button>
                </div>
            </div>
        </div>
    </form>
@endsection
@section('extra-footer-scripts')
    <script src="{{asset('js/employees/create.js')}}"></script>
@endsection